### ISSUE TITLE
怎么样实现你说的包装两RealRichText来展示一个未知大小的图片。

### ISSUE THREAD

**Issue by zucchiniEvader** [limengyun2008/RealRichText#2]
我现在的问题是我要从互联网上获取图片，但是图片的大小我不知道。我又不想写死，因为图片有大有小，所以我现在想按照图片的大小显示。请问最后面说的那种方式具体该怎么实现呢？

**Comment by limengyun2008** [comment]
一个StatefulWidget 没有图片的时候所有图片都是写死的一个loading placeholder图片，loading placeholder图片总归是有宽高的。任何一个图片宽高信息获取到了之后之后setState一下 重新build一次就好了呀
